frontpage:
    path: /
    defaults:  { _controller: BlueCode\Controller\DocController::frontpageAction }

# Authentication
login:
    path: /login
    defaults:  { _controller: BlueCode\Controller\AuthenticationController::loginAction }
    
login_check:
    path: /authentication/login_check

# Assets

assets:
    path: /.{postfix}
    defaults: { _controller: BlueCode\Controller\AssetsController::serveAction }
    requirements:
        postfix: .+
        
# Projects

projects_index:
    path: /projects
    defaults:  { _controller: BlueCode\Controller\DocController::indexAction }

projects_view:
    path: /projects/{projectCode}
    defaults:  { _controller: BlueCode\Controller\DocController::viewAction }

projects_routes_index:
    path: /projects/{projectCode}/routes
    defaults:  { _controller: BlueCode\Controller\DocController::routeIndexAction }

projects_routes_view:
    path: /projects/{projectCode}/routes/{routeName}
    defaults:  { _controller: BlueCode\Controller\DocController::routeViewAction }

projects_tables_index:
    path: /projects/{projectCode}/tables
    defaults:  { _controller: BlueCode\Controller\DocController::tableIndexAction }

projects_tables_view:
    path: /projects/{projectCode}/tables/{tableName}
    defaults:  { _controller: BlueCode\Controller\DocController::tableViewAction }

# API routes

api_root:
    path: /api/v1
    defaults:  { _controller: BlueCode\Controller\ApiController::rootAction }
