#!/usr/bin/env php
<?php

require_once(__DIR__.'/../vendor/autoload.php');

use Symfony\Component\Console\Application;

$application = new Application('BlueCode toolkit', '1.0.0');
$application->setCatchExceptions(false);
$application->add(new \BlueCode\Command\ExampleCommand());
$application->run();
